### ISSUE TITLE
Hapdup did not generate expected folder/files

### ISSUE THREAD

**Issue by EDISON2022W** [KolmogorovLab/hapdup#31]
Hello

I ran the hapdup using the command lines below 
########################
singularity pull docker://mkolmogo/hapdup:0.12
HD_DIR='pwd'
singularity exec --bind $HD_DIR hapdup_0.12.sif \
  hapdup --assembly $HD_DIR/assembly.fasta --bam $HD_DIR/lr_mapping.bam --out-dir $HD_DIR/hapdup -t 46 --rtype ont
#######################
No error popped up during running.
In the results folder, there are

filtered.bam
filtered.bam.bai
pepper
margin
hapdup.log
flye_hap_1 (bubbles_1.fasta flye.log consensus_1.fasta)
flye_hap_2 (bubbles_2.fasta flye.log consensus_2.fasta)

As the instruction, hapdup_dual_{1,2}.fasta, phased_blocks_hp{1,2}.bed, hapdup_phased_{1,2}.fasta should be generated at the end of running, however, I did not find these files.

Any suggestions?

In the stdout 

" Of 5340304 variants: wrote 5340304 with 3693691 phased; skipped 0 for region, 1487317 for not being analyzed, 158813 for being homozygous, 483 for disagreement with margin
  Identified 8387 phase sets with lengths avg:330692, min:-61379, max:6459426, N50:1367296". 

Does that mean I should get phased contigs with N50 1367296?

Thanks

**Comment by fenderglass** [comment]
Sorry for my late response!

Yes, it seems that Hapdup did not finish that last parts of the pipeline, although unclear why. According to the Margin output, you should get phased contigs with N50 ~1.3Mb as you said. Most likely reason is that it was killed due to excessive resource usage..

Could you please share (i) `hapdup.log` (ii) the contents of `flye_hap{1,2}` dirs and `flye.log` files inside them? Also, if you still have it, could you share the full terminal output.

**Comment by EDISON2022W** [comment]
I re-downloaded the sif file and it works now.
